name: yousentech_pos_dashboard
description: "A new Flutter package project."
version: 1.0.0
homepage:

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  intl: ^0.20.2
  font_awesome_flutter: ^10.7.0
  popover:

  # pos_shared_preferences:
  #   git:
  #     url: https://github.com/YousenTech-Flutter/yousentech_pos_shared_preferences.git
  #     ref: master
  # shared_widgets:
  #   git:
  #     url: https://github.com/YousenTech-Flutter/yousentech_pos_shared_widgets.git
  #     ref: master
  # yousentech_authentication:
  #   git:
  #     url: https://github.com/YousenTech-Flutter/yousentech_authentication.git
  #     ref: master
  # yousentech_pos_loading_synchronizing_data:
  #   git:
  #     url: https://github.com/YousenTech-Flutter/yousentech_pos_loading_synchronizing_data.git
  #     ref: master
  # yousentech_pos_basic_data_management:
  #   git:
  #     url: https://github.com/YousenTech-Flutter/yousentech_pos_basic_data_management.git
  #     ref: master
  # yousentech_pos_session:
  #   git:
  #     url: https://github.com/YousenTech-Flutter/yousentech_pos_session.git
  #     ref: master
  # yousentech_pos_session_list_with_report:
  #   git:
  #     url: https://github.com/YousenTech-Flutter/yousentech_pos_session_list_with_report.git
  #     ref: master
  # yousentech_pos_final_report:
  #   git:
  #     url: https://github.com/YousenTech-Flutter/yousentech_pos_final_report.git
  #     ref: master
  # yousentech_pos_payment:
  #   git:
  #     url: https://github.com/YousenTech-Flutter/yousentech_pos_payment.git
  #     ref: master
  # yousentech_pos_notification_history:
  #   git:
  #     url: https://github.com/YousenTech-Flutter/yousentech_pos_notification_history.git
  #     ref: master
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  assets:
    - assets/image/
  # To add assets to your package, add an assets section, like this:
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Medium.ttf
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Bold.ttf
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
